### ISSUE TITLE
Installation instructions missing a dependency and prerequisite

### ISSUE THREAD

**Issue by mrbluecoat** [pcollinson/nftfw#1]
FYI, https://github.com/pcollinson/nftfw/blob/master/docs/Installation.md is missing a dependency: `python3-setuptools` and a prerequisite: `pip3 install wheel`

**Comment by pcollinson** [comment]
I seem to have the python3-setuptools and python3-wheel packages installed automatically on my systems. It's unclear to me where they came from, they are recommended by the python3-pip package. Will changing the line
```
$ sudo apt install python3-pip
```
to
```
$ sudo apt install python3-pip python3-setuptools python3-wheel
```
fix this?

**Comment by pcollinson** [comment]
I've changed the installation instructions on V0.7.3 to include these two packages. Let me know if this is not a solution.

**Comment by mrbluecoat** [comment]
That worked - thanks!
