### ISSUE TITLE
Feature request: non-interactive install

### ISSUE THREAD

**Issue by mrbluecoat** [pcollinson/nftfw#2]
For situations where a non-interactive install is preferred, can you update https://github.com/pcollinson/nftfw/blob/master/Install.sh to read from an optional config file or accept arguments instead of `yesno` and `read newuser`?

**Comment by pcollinson** [comment]
This is a good idea. I'll see what can be done.

**Comment by pcollinson** [comment]
Version 0.7.3 now does this. See the file Autoinstall.default for how to make it so

**Comment by mrbluecoat** [comment]
Nice solution.  FYI, you'll need to change your instructions from `sh Install.sh` to `bash Install.sh` to make it work.

**Comment by pcollinson** [comment]
Hmm.  I suspect that the problem was that it couldn't find the Autoinstall.conf file in dash.. which I presume you were using. I've fixed that. The change is to find:
```
. Autoinstall.conf
```
and replace it by
```
. ./Autoinstall.conf
```
The next release will include the fixed script.

**Comment by pcollinson** [comment]
Version 0.7.4 fixes the shell script issue. I am trying to make things dash compliant.

**Comment by mrbluecoat** [comment]
Working, thx
