### ISSUE TITLE
Custom nft commands supported?

### ISSUE THREAD

**Issue by mrbluecoat** [pcollinson/nftfw#4]
Does nftfw support custom nft commands?  For example, I'd like to make sure this table and contents always gets added when nft rewrites the nftables:

```
nft add table nat
nft 'add chain nat prerouting { type nat hook prerouting priority -100; }'
nft 'add chain nat postrouting { type nat hook postrouting priority 100; }'
nft add rule nat prerouting tcp dport domain redirect
nft add rule nat prerouting udp dport domain redirect
nft add rule nat postrouting masquerade
```
I see https://github.com/pcollinson/nftfw/blob/master/etc_nftfw/nftfw_init.nft#L146-L189 but no area for custom entries.

**Comment by pcollinson** [comment]
Yes you can edit etc/nftfw/nftfw_init.nft. This is there to be changed. I use nftfw on my local firewall/router machine - you can find it's nftfw_init.nft in etc/nftfw/original/router_example.

**Comment by pcollinson** [comment]
This highlighted a small hole in the documentation, which I've hopefully filled with a change to the[ How Do I ](https://github.com/pcollinson/nftfw/blob/master/docs/How_do_I.md) document and the [nftfw-files](https://github.com/pcollinson/nftfw/blob/master/docs/man/nftfw-files.5.md) manual page.
