### ISSUE TITLE
nftfw - outbound generation

### ISSUE THREAD

**Issue by syndicateops** [pcollinson/nftfw#6]
Love the project.
 tinkering with it has opened up many new avenues of thought regarding more dynamic uses of nftables.    i still have much to learn in integrating nftfw
I am curious if nftfw can be configured to instead of blacklisting hosts based on IP address.. instead create the observed input & output chain rules?

being able to capture a known-good state of the traffic would save alot of time!

thank you

   

I

**Comment by pcollinson** [comment]
Not quite sure what you are after. If the nftfw source directories are empty, ie nftfw/{blacklist.d, whitelist.d, blacknets.d}, then nftfw will create the nftables rule set - which you can see in /etc/nftfables.conf if you've configured nftfw to use that. 
You can also disable blacklist and whitelist generation by creating an empty file called 'disabled' in the appropriate directory (actually I failed to implement this for blacknets.d - and that's on my list for the future).

The nft command can be used to list the live rules in the kernel. I tend to use two shell aliases to make looking at the rules easier:

```
alias nfl='sudo nft list ruleset ip | less'
alias nfl6='sudo nft list ruleset ip6 | less'
```

I've never thought about providing a 'dry run' option which would list what is being dropped while accepting packets. However, this is reasonably easy to configure by editing the /etc/nftfw/nftfw_init.nft template file. All the standard rules drop and reject packets by jumping to the dropcounter and rejectcounter tables respectively. Inserting a line at the top of these tables like:

```
counter log prefix "Drop " accept
```

(change the log text to taste) will make them accept the packet and put copious lines into syslog. However, analysing this will not be that easy. It's probably better to use packet capture tools like tcpdump and Wireshark.

If you change the nftfw_init.nft file make sure you reload nftfw using

```
nftfw -f load
```
to force a complete rebuild.

If you are wondering what rules to install for inbound detection, then netstat -pat will tell you what you system is listening for, and that's my general starting point for configuring inbound rules.

**Comment by syndicateops** [comment]
"the creation of a set of outbound rules"
 -Yes i think your on the same page.  ability to generating rules like your showing in the above comment would save soo much time.   
i will try your suggestion & see if i can get it working..!

Here's a frequent scenario:
Autonomous application-pool networks are switched together to host the service
Any one application-pool of hosts can talk east-west with each other without much restriction. 
Hosts between different application-pools needs to talk to the others pool, but on limited & filtered ports. 
Without webservers & public internet its just local network traffic so capturing it like this i think would save alot of time & effort.
