### ISSUE TITLE
Adding blanket multicast support rules & 0.0.0.0

### ISSUE THREAD

**Issue by syndicateops** [pcollinson/nftfw#8]
i've recently had to add support to ensure internal multicast traffic is explicitly not messed with in addition to some sets i have whitelisting host access between some subnets.
I was able to generate the host list based on prior advice you gave & that is appreciated!   -thanks again for the tips

From some wiresharking i found this one unique situation where a piece of equipment was having the last part of a dhcp handshake blocked..  it turned out if i allowed 0.0.0.0 then the full handshake could take place.
however this makes me a little nervous as an accept rule. 

i can share a sanitized version of the .conf if your willing to take a peak?

thank you,

**Comment by pcollinson** [comment]
Can you use the contact form [nftfw.uk.contact.php](https://nftfw.uk/contact.php) to send me you email address, I'll reply and this conversation can not be public.
